modLoader="javafml"
loaderVersion="[25,)"
logoFile="logo.png"

[[mods]]
modId="lightarea"
version="${version}"
displayName="LightArea"
displayURL="https://github.com/Himmelt/LightArea"
credits="Himmelt, making this mod."
authors="Himmelt"
description='''
Light Area Mod , Copyright (c) 2018-2020 Himmelt.
'''
